Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 29, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bot/home.html
"GET / HTTP/1.1" 500 86496
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 29, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bot/home.html
"GET / HTTP/1.1" 500 86906
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 29, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bot/home.html
"GET / HTTP/1.1" 500 85514
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 29, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bot/home.html
"GET / HTTP/1.1" 500 85502
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 29, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bot/home.html
"GET / HTTP/1.1" 500 85394
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 29, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bot/home.html
"GET / HTTP/1.1" 500 85514
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 29, in home
    return render(request, 'bot/templates/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bot/templates/home.html
"GET / HTTP/1.1" 500 85674
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 29, in home
    return render(request, 'bot/templates/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: bot/templates/home.html
"GET / HTTP/1.1" 500 86057
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: bot/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 29, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: bot/base.html
"GET / HTTP/1.1" 500 137300
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /accounts/login/?next=/ HTTP/1.1" 500 135298
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/accounts/views.py", line 18, in register
    user = form.save()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/forms.py", line 151, in save
    user.save()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/tim/VScode Projects/Sickpuntv2/accounts/models.py", line 31, in create_user_profile
    UserProfile.objects.create(user=instance)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/tim/VScode Projects/Sickpuntv2/accounts/models.py", line 16, in save
    self.betfair_password = f.encrypt(self.betfair_password.encode())
AttributeError: 'bytes' object has no attribute 'encode'
"POST /accounts/register/ HTTP/1.1" 500 113739
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 65, in testing_view
    return render(request, 'betfair_bot/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/testing.html
"GET /testing/ HTTP/1.1" 500 92654
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 33, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'testing_results' not found. 'testing_results' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 153338
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 65, in testing_view
    return render(request, 'betfair_bot/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/testing.html
"GET /testing/ HTTP/1.1" 500 92654
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 65, in testing_view
    return render(request, 'betfair_bot/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/testing.html
"GET /testing/ HTTP/1.1" 500 92654
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 65, in testing_view
    return render(request, 'betfair_bot/templates/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/templates/testing.html
"GET /testing/ HTTP/1.1" 500 92864
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 65, in testing_view
    return render(request, 'templates/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: templates/testing.html
"GET /testing/ HTTP/1.1" 500 92612
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 65, in testing_view
    return render(request, 'betfair_bot/templates/bot/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/templates/bot/testing.html
"GET /testing/ HTTP/1.1" 500 92940
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 65, in testing_view
    return render(request, 'betfair_bot/templates/bot/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/templates/bot/testing.html
"GET /testing/ HTTP/1.1" 500 92940
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 33, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'betfair_bot/testing' not found. 'betfair_bot/testing' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 153148
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 33, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'betfair_bot/testing' not found. 'betfair_bot/testing' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 153305
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 65, in testing_view
    return render(request, 'betfair_bot/templates/bot/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/templates/bot/testing.html
"GET /testing/ HTTP/1.1" 500 92940
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 45, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'barrier_number' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 130345
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 45, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'barrier_number' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 130345
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 40, in testing_view
    barrier_number = form.cleaned_data['barrier_number']
KeyError: 'barrier_number'
"POST /testing/ HTTP/1.1" 500 77519
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 66, in testing_view
    return render(request, 'betfair_bot/testing.html', {'form': form})
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/testing.html
"GET /testing/ HTTP/1.1" 500 92680
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 66, in testing_view
    return render(request, 'betfair_bot/templates/bot/testing.html', {'form': form})
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/templates/bot/testing.html
"GET /testing/ HTTP/1.1" 500 92974
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 66, in testing_view
    return render(request, 'betfair_bot/templates/bot/testing.html', {'form': form})
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/templates/bot/testing.html
"GET /testing/ HTTP/1.1" 500 92974
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 64, in testing_view
    return render(request, 'betfair_bot/templates/bot/testing.html', {'form': form})
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/templates/bot/testing.html
"GET /testing/ HTTP/1.1" 500 92299
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 64, in testing_view
    return render(request, 'betfair_bot/templates/bot/testing.html', {'form': form})
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: betfair_bot/templates/bot/testing.html
"GET /testing/ HTTP/1.1" 500 92299
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 64, in testing_view
    return render(request, 'bot/testing.html', {'form': form})
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /testing/ HTTP/1.1" 500 142123
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 68, in testing_view
    return render(request, 'bot/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /testing/ HTTP/1.1" 500 142998
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: bot/base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 32, in home
    return render(request, 'bot/home.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: bot/base.html
"GET / HTTP/1.1" 500 143890
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 162, in cert
    cert_path = os.listdir(self.certs)
FileNotFoundError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 48, in request
    cert=self.client.cert,
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 164, in cert
    raise CertsError(str(e))
betfairlightweight.exceptions.CertsError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 35, in home
    api_client.login()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 30, in __call__
    (response, response_json, elapsed_time) = self.request(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 54, in request
    raise APIError(None, exception=e)
betfairlightweight.exceptions.APIError: None 
Params: None 
Exception: [Errno 2] No such file or directory: '/certs'
"GET / HTTP/1.1" 500 97389
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 162, in cert
    cert_path = os.listdir(self.certs)
FileNotFoundError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 48, in request
    cert=self.client.cert,
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 164, in cert
    raise CertsError(str(e))
betfairlightweight.exceptions.CertsError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 35, in home
    api_client.login()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 30, in __call__
    (response, response_json, elapsed_time) = self.request(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 54, in request
    raise APIError(None, exception=e)
betfairlightweight.exceptions.APIError: None 
Params: None 
Exception: [Errno 2] No such file or directory: '/certs'
"GET / HTTP/1.1" 500 97389
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 37, in home
    api_client.login()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 30, in __call__
    (response, response_json, elapsed_time) = self.request(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 64, in request
    self._error_handler(response_json)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 71, in _error_handler
    raise self._error(response)
betfairlightweight.exceptions.LoginError: API login: CERT_AUTH_REQUIRED
"GET / HTTP/1.1" 500 89504
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 37, in home
    api_client.login()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 30, in __call__
    (response, response_json, elapsed_time) = self.request(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 64, in request
    self._error_handler(response_json)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 71, in _error_handler
    raise self._error(response)
betfairlightweight.exceptions.LoginError: API login: CERT_AUTH_REQUIRED
"GET / HTTP/1.1" 500 89652
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 162, in cert
    cert_path = os.listdir(self.certs)
FileNotFoundError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 48, in request
    cert=self.client.cert,
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 164, in cert
    raise CertsError(str(e))
betfairlightweight.exceptions.CertsError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 37, in home
    api_client.login()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 30, in __call__
    (response, response_json, elapsed_time) = self.request(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 54, in request
    raise APIError(None, exception=e)
betfairlightweight.exceptions.APIError: None 
Params: None 
Exception: [Errno 2] No such file or directory: '/certs'
"GET / HTTP/1.1" 500 97609
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 162, in cert
    cert_path = os.listdir(self.certs)
FileNotFoundError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 48, in request
    cert=self.client.cert,
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 164, in cert
    raise CertsError(str(e))
betfairlightweight.exceptions.CertsError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 37, in home
    api_client.login()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 30, in __call__
    (response, response_json, elapsed_time) = self.request(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 54, in request
    raise APIError(None, exception=e)
betfairlightweight.exceptions.APIError: None 
Params: None 
Exception: [Errno 2] No such file or directory: '/certs'
"GET / HTTP/1.1" 500 97609
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 162, in cert
    cert_path = os.listdir(self.certs)
FileNotFoundError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 48, in request
    cert=self.client.cert,
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 164, in cert
    raise CertsError(str(e))
betfairlightweight.exceptions.CertsError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 37, in home
    api_client.login()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 30, in __call__
    (response, response_json, elapsed_time) = self.request(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 54, in request
    raise APIError(None, exception=e)
betfairlightweight.exceptions.APIError: None 
Params: None 
Exception: [Errno 2] No such file or directory: '/certs'
"GET / HTTP/1.1" 500 97609
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 162, in cert
    cert_path = os.listdir(self.certs)
FileNotFoundError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 48, in request
    cert=self.client.cert,
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 164, in cert
    raise CertsError(str(e))
betfairlightweight.exceptions.CertsError: [Errno 2] No such file or directory: '/certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 37, in home
    api_client.login()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 30, in __call__
    (response, response_json, elapsed_time) = self.request(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/endpoints/login.py", line 54, in request
    raise APIError(None, exception=e)
betfairlightweight.exceptions.APIError: None 
Params: None 
Exception: [Errno 2] No such file or directory: '/certs'
"GET / HTTP/1.1" 500 98337
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 74, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'barrier_number' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 130706
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 123, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'barrier_number' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 130856
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 65, in home
    if not login_result['success']:
TypeError: 'NoneType' object is not subscriptable
"GET / HTTP/1.1" 500 76865
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 71, in home
    market_data = api_client.betting.list_market_catalogue(
AttributeError: 'APIClient' object has no attribute 'betting'
"GET / HTTP/1.1" 500 77114
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 94, in home
    market_data = api_client.betting.list_market_catalogue(
AttributeError: 'APIClient' object has no attribute 'betting'
"GET / HTTP/1.1" 500 77114
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 78, in home
    api_client = APIClient(
TypeError: APIClient() takes no arguments
"GET / HTTP/1.1" 500 76345
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/http/request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/messages/storage/cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/messages/middleware.py", line 12, in process_request
    request._messages = default_storage(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/messages/storage/__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/messages/storage/fallback.py", line 16, in __init__
    self.storages = [
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/messages/storage/fallback.py", line 17, in <listcomp>
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/messages/storage/cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/conf/__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 21, in home
    api_client = APIClient(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/apiclient.py", line 34, in __init__
    super(APIClient, self).__init__(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 94, in __init__
    self.get_app_key()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 126, in get_app_key
    raise AppKeyError(self.username)
betfairlightweight.exceptions.AppKeyError: AppKey not found in .bashprofile for penjud, add or pass to APIClient
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 22, in home
    api_client = APIClient(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/apiclient.py", line 34, in __init__
    super(APIClient, self).__init__(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 93, in __init__
    self.get_password()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 114, in get_password
    raise PasswordError(self.username)
betfairlightweight.exceptions.PasswordError: Password not found in .bashprofile for penjud, add or pass to APIClient
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 35, in home
    market_filter = logging.Filter.market_filter(text_query='horse racing')
AttributeError: type object 'Filter' has no attribute 'market_filter'
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 37, in home
    market_filter = logging.Filter.market_filter(text_query='horse racing')
AttributeError: type object 'Filter' has no attribute 'market_filter'
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 24, in home
    api_client = betfairlightweight.APIClient(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/apiclient.py", line 34, in __init__
    super(APIClient, self).__init__(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 93, in __init__
    self.get_password()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/betfairlightweight/baseclient.py", line 114, in get_password
    raise PasswordError(self.username)
betfairlightweight.exceptions.PasswordError: Password not found in .bashprofile for penjud, add or pass to APIClient
"GET / HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 91, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'barrier_number' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 91, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'barrier_number' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 91, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'barrier_number' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 96, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'odds' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 96, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'race_date' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 96, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'track_conditions' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 92, in testing_view
    form.track_conditions = form.cleaned_data['form.track_conditions']
KeyError: 'form.track_conditions'
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 91, in testing_view
    horse_barrier = form.cleaned_data.get['horse_barrier']
TypeError: 'builtin_function_or_method' object is not subscriptable
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 98, in testing_view
    form_track_conditions=form.cleaned_data['track_conditions'],  # Replace "form_track_conditions" with "track_conditions"
KeyError: 'track_conditions'
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 98, in testing_view
    track_conditions=form.cleaned_data['track_conditions'],  # Replace "form_track_conditions" with "track_conditions"
KeyError: 'track_conditions'
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 96, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'track_conditions' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 108, in testing_view
    form = TestingForm()  # or PlaceBetForm() based on what you want to display initially
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/forms.py", line 19, in __init__
    self.fields['race_date'].widget = SelectDateWidget(years=range(2001, current_year + 1))
KeyError: 'race_date'
"GET /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 93, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'barrier_number' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 93, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'country_code' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 93, in testing_view
    historical_data = BetfairData.objects.filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'country_code' into field. Choices are: age_restrictions, class_restrictions, form_barrier, form_class, form_distance, form_jockey, form_margin, form_meeting_date, form_name, form_other_runners, form_position, form_price, form_time, form_track, form_track_condition, form_weight, horse_age, horse_barrier, horse_claim, horse_jockey, horse_last10, horse_name, horse_number, horse_prize_money, horse_record, horse_record_dead, horse_record_distance, horse_record_fast, horse_record_first_up, horse_record_good, horse_record_heavy, horse_record_jumps, horse_record_second_up, horse_record_slow, horse_record_track, horse_record_track_distance, horse_sex, horse_trainer, horse_weight, id, meeting_date, race_number, race_prizemoney, start_time, track, weight_restrictions
"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column betfair_bot_betfairdata.country_code does not exist
LINE 1: SELECT "betfair_bot_betfairdata"."id", "betfair_bot_betfaird...
                                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 106, in testing_view
    return render(request, 'bot/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 325, in render
    if match:
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 414, in __bool__
    self._fetch_all()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column betfair_bot_betfairdata.country_code does not exist
LINE 1: SELECT "betfair_bot_betfairdata"."id", "betfair_bot_betfaird...
                                               ^

"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /testing/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column betfair_bot_betfairdata.country_code does not exist
LINE 1: SELECT "betfair_bot_betfairdata"."id", "betfair_bot_betfaird...
                                               ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 106, in testing_view
    return render(request, 'bot/testing.html', context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 325, in render
    if match:
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 414, in __bool__
    self._fetch_all()
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column betfair_bot_betfairdata.country_code does not exist
LINE 1: SELECT "betfair_bot_betfairdata"."id", "betfair_bot_betfaird...
                                               ^

"POST /testing/ HTTP/1.1" 500 145
Internal Server Error: /race-selection/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 132, in race_selection
    races = betfair_api.get_races()  # Implement the get_races() method in the BetfairAPI class
AttributeError: 'BetfairAPI' object has no attribute 'get_races'
"GET /race-selection/ HTTP/1.1" 500 145
Internal Server Error: /race-selection/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 132, in race_selection
    races = betfair_api.get_races()  # Implement the get_races() method in the BetfairAPI class
AttributeError: 'BetfairAPI' object has no attribute 'get_races'
"GET /race-selection/ HTTP/1.1" 500 145
Internal Server Error: /race-selection/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 133, in race_selection
    return render(request, 'race_selection.html', {'races': races})
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: race_selection.html
"GET /race-selection/ HTTP/1.1" 500 145
Internal Server Error: /race-selection/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 134, in race_selection
    return render(request, 'race_selection.html', {'races': None})
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: race_selection.html
"GET /race-selection/ HTTP/1.1" 500 145
Internal Server Error: /race-selection/
Traceback (most recent call last):
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tim/VScode Projects/Sickpuntv2/betfair_bot/views.py", line 134, in race_selection
    return render(request, 'race_selection.html', {'races': None})
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/tim/VScode Projects/Sickpuntv2/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: race_selection.html
"GET /race-selection/ HTTP/1.1" 500 145
